
export enum AppStep {
  LANDING = 'LANDING',
  TRANSITION = 'TRANSITION',
  QUIZ = 'QUIZ',
  CALCULATING = 'CALCULATING',
  ATTENTION_AUDIO = 'ATTENTION_AUDIO',
  DIAGNOSIS_LOADING = 'DIAGNOSIS_LOADING',
  DIAGNOSIS = 'DIAGNOSIS',
  DISCOUNT_SCRATCH = 'DISCOUNT_SCRATCH',
  RESULTS_PROOF = 'RESULTS_PROOF',
  RESULT = 'RESULT'
}

export interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
}
